name: Power Apps Solution Import (Service Principal)

on:
  push:
    paths:
      - "solutions/EmpLeave.zip"
    branches:
      - main
  workflow_dispatch:

jobs:
  import-to-test:
    name: Import to Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
         dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.29.11
         export PATH="$PATH:$HOME/.dotnet/tools"
         pac --version

      - name: Authenticate Service Principal (Test)
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          pac auth create --name TestSP \
                          --applicationId ${{ secrets.POWERPLATFORM_APP_ID }} \
                          --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} \
                          --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} \
                          --url ${{ secrets.TEST_ENV_URL }}

      - name: Import Solution to Test
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          pac solution import --path solutions/EmpLeave.zip \
                              --overwrite-unmanaged-customizations \
                              --publish-changes \
                              --name TestSP

  import-to-prod:
    name: Import to Production Environment
    runs-on: ubuntu-latest
    needs: import-to-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PAC CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.29.11
          export PATH="$PATH:$HOME/.dotnet/tools"
          pac version

      - name: Authenticate Service Principal (Prod)
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          pac auth create --name ProdSP \
                          --applicationId ${{ secrets.POWERPLATFORM_APP_ID }} \
                          --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} \
                          --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} \
                          --url ${{ secrets.PROD_ENV_URL }}

      - name: Import Solution to Prod
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          pac solution import --path solutions/EmpLeave.zip \
                              --overwrite-unmanaged-customizations \
                              --publish-changes \
                              --name ProdSP
