name: Power Apps Solution Import (Service Principal)

on:
  push:
    paths:
      - "solutions/EmpLeave.zip"
    branches:
      - main
  workflow_dispatch:

jobs:
  import-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Power Platform CLI via .NET CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.29.11
          pac --version
        shell: bash

      - name: Authenticate with Service Principal
        run: |
          pac auth create --name TestSP \
                          --applicationId ${{ secrets.POWERPLATFORM_APP_ID }} \
                          --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} \
                          --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} \
                          --url ${{ secrets.TEST_ENV_URL }}

      - name: Import Solution to Test
        run: |
          pac solution import --path solutions/EmpLeave.zip \
                              --overwrite-unmanaged-customizations \
                              --publish-changes \
                              --environment ${{ secrets.TEST_ENV_URL }}

  import-to-prod:
    runs-on: ubuntu-latest
    needs: import-to-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Power Platform CLI via .NET CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.29.11
          pac --version
        shell: bash

      - name: Authenticate with Service Principal
        run: |
          pac auth create --name ProdSP \
                          --applicationId ${{ secrets.POWERPLATFORM_APP_ID }} \
                          --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} \
                          --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} \
                          --url ${{ secrets.PROD_ENV_URL }}

      - name: Import Solution to Prod
        run: |
          pac solution import --path solutions/EmpLeave.zip \
                              --overwrite-unmanaged-customizations \
                              --publish-changes \
                              --environment ${{ secrets.PROD_ENV_URL }}
